#ifndef __CONFIG_H__
#define __CONFIG_H__
#define CONFIG_VOXIA_VERSION "0.1.0"
#define CONFIG_LOG_VERBOSE 1
#define CONFIG_PHYS_MAX_WINDOW_COUNT 8
#define CONFIG_PAGING_MAX_MAPPED_DATA_COUNT 512
#endif // __CONFIG_H__
