#ifndef __FIRMW__SUB__USB__CLASSCODE_H__
#define __FIRMW__SUB__USB__CLASSCODE_H__

#define USB_CLASS_AUDIO 0X1
#define USB_CLASS_COMM 0X2
#define USB_CLASS_HID 0X3
#define USB_CLASS_PHYSICAL 0X5
#define USB_CLASS_IMAGE 0X6
#define USB_CLASS_PRINTER 0X7
#define USB_CLASS_MASS_STORAGE 0X8
#define USB_CLASS_HUB 0X9
#define USB_CLASS_CDC_DATA 0X0A
#define USB_CLASS_SMART_CARD 0X0B
#define USB_CLASS_CONTENT_SECURITY 0X0D
#define USB_CLASS_VIDEO 0X0E
#define USB_CLASS_PERSONAL_HEALTHCARE 0X0F
#define USB_CLASS_DIAGNOSTIC_DEVICE 0XFE
#define USB_CLASS_WIRELESS 0XE0
#define USB_CLASS_MISC 0XEF
#define USB_CLASS_APP_SPECIFIC 0XFE
#define USB_CLASS_VENDOR_SPECIFIC 0XFF

#endif // __FIRMW__SUB__USB__CLASSCODE_H__