// Auto-generated from .config
 #define VOXIA_VERSION "0.1.2"
 #define VOXIA_LOG_VERBOSE 1
 #define VOXIA_LOG_LEVEL 3
 #define VOXIA_ENABLE_SERIAL_OUTPUT 1
 #define VOXIA_PHYS_MAX_WINDOW_COUNT 64
 #define VOXIA_PAGING_MAX_MAPPED_DATA_COUNT 512
 #define VOXIA_MAX_CORE 25
 #define VOXIA_MAX_NUMBER_THREAD 65536
 #define VOXIA_THREAD_MAX_BLOB 4096
 #define VOXIA_MAX_SCHEDULER_TIME_MS 100
 #define VOXIA_MAX_WORKQUEUE_EACH_CORE 256
 #define VOXIA_DEFAULT_VOXMO_PATH "/init/modules/"
 #define VOXIA_INITRD_MOUNT_PATH "/init"
 #define VOXIA_VFS_CACHE_BLOB_SIZE 4096
 #define VOXIA_VFS_CACHE_TTL_MS 5000
